### ISSUE TITLE
Issue with Rate Request Service PurposeofShipmentType is not defined

### ISSUE THREAD

**Issue by adityaduggal** [python-fedex-devs/python-fedex#96]
Hi,
I am trying to implement this awesome fedex wrapper in my application but I am getting this error when I am trying to make a Rate Request, this is primarily because the PurposeofShipmentType is not defined in the rate request and this is the error I am getting when I fire the rate request from the system.

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 81, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 36, in runserverobj
    r = doc.run_method(method)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1029, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1012, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/rigpl_erpnext/rigpl_erpnext/rigpl_erpnext/doctype/book_shipment/book_shipment.py", line 26, in get_rates
    self.rate_service(credentials, from_address_doc, to_address_doc, from_country_doc, to_country_doc, transporter_doc)
  File "/home/frappe/frappe-bench/apps/rigpl_erpnext/rigpl_erpnext/rigpl_erpnext/doctype/book_shipment/book_shipment.py", line 151, in rate_service
    rate_request.send_request()
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/fedex/base_service.py", line 331, in send_request
    self._check_response_for_request_errors()
  File "/home/frappe/frappe-bench/env/lib/python2.7/site-packages/fedex/base_service.py", line 265, in _check_response_for_request_errors
    notification.Message)
FedexError: The PurposeOfShipmentType is null, empty or invalid. (Error code: 691)
```

The surprising part is that I am unable to get the error code 691 in the API documentation.

**Comment by adityaduggal** [comment]
hi @gtaylor 
I think I need to add Purpose to the rate_request being sent to fedex but  I unable to do the same kindly let me know if you can just tell me how to add this simple purpose to my rate_request mentioned in RateService_v18.wsdl as under
https://github.com/python-fedex-devs/python-fedex/blob/6f60800aa7538aa7b2eea2758aa5508d92cfb376/fedex/wsdl/RateService_v18.wsdl#L363

I am trying to add the request by this below code:
`rate_request.CommercialInvoice.Purpose` but I am getting an error on the same, would I need to change the code of your repository or I am doing something wrong.

Please let me know since I am not a very good coder as such and more like a newbie.

**Comment by radzhome** [comment]
To add optional stuff use `create_wsdl_object_of_type` as shown in the examples.
